/**
 * @file codop.c
 *
 * Departamento de Informática de Sistemas y Computadores (DISCA)
 * Universidad Politécnica de Valencia.
 *
 * @author Sergio Sáez <ssaez@disca.upv.es>
 * @author Pedro López <plopez@disca.upv.es>
 *
 * @brief
 *    Contiene la definición de las instrucciones
 *
 * DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
 *
 * @copyright [CC BY-NC-ND 4.0]
 *   Esta obra está bajo una licencia de Creative Commons Atribución-NoComercial-SinDerivadas
 *   Para evitar dudas, no se tiene permiso bajo esta Licencia para compartir Material Adaptado.
 *   Más detalles en https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.es
 */

#define codop_C

/***** Definiciones Externas **********************************/

#include "tipos.h"
#include "instrucciones.h"
#include "codop.h"

/***** Variables globales *************************************/

inst_types_t inst_types_list[] = {
    // INST_TYPE_nnnn
    {t_ninguno, t_ninguno, t_ninguno, t_ninguno},
    // INST_TYPE_nLSn
    {t_ninguno, t_dword, t_float, t_ninguno},
    // INST_TYPE_nLLn
    {t_ninguno, t_dword, t_dword, t_ninguno},
    // INST_TYPE_nLDn
    {t_ninguno, t_dword, t_double, t_ninguno},
    // INST_TYPE_SSnn
    {t_float, t_float, t_ninguno, t_ninguno},
    // INST_TYPE_SSSn
    {t_float, t_float, t_float, t_ninguno},
    // INST_TYPE_SSSS
    {t_float, t_float, t_float, t_float},
    // INST_TYPE_SLnn
    {t_float, t_dword, t_ninguno, t_ninguno},
    // INST_TYPE_Lnnn
    {t_dword, t_ninguno, t_ninguno, t_ninguno},
    // INST_TYPE_LnLn
    {t_dword, t_ninguno, t_dword, t_ninguno},
    // INST_TYPE_LSnn
    {t_dword, t_float, t_ninguno, t_ninguno},
    // INST_TYPE_LSSn
    {t_dword, t_float, t_float, t_ninguno},
    // INST_TYPE_LLnn
    {t_dword, t_dword, t_ninguno, t_ninguno},
    // INST_TYPE_LLLn
    {t_dword, t_dword, t_dword, t_ninguno},
    // INST_TYPE_LDnn
    {t_dword, t_double, t_ninguno, t_ninguno},
    // INST_TYPE_LDDn
    {t_dword, t_double, t_double, t_ninguno},
    // INST_TYPE_DLnn
    {t_double, t_dword, t_ninguno, t_ninguno},
    // INST_TYPE_DDnn
    {t_double, t_double, t_ninguno, t_ninguno},
    // INST_TYPE_DDDn
    {t_double, t_double, t_double, t_ninguno},
    // INST_TYPE_DDDD
    {t_double, t_double, t_double, t_double}
};

inst_fmt_t instruction_list[] = {
    // RV32I_ADDI
    {RV32I, "addi", "+", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SLTI
    {RV32I, "slti", "<", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM, .funct3=0b010, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SLTIU
    {RV32I, "sltiu", "<", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM, .funct3=0b011, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_ANDI
    {RV32I, "andi", "&", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM, .funct3=0b111, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_ORI
    {RV32I, "ori", "|", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM, .funct3=0b110, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_XORI
    {RV32I, "xori", "^", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM, .funct3=0b100, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_LUI
    {RV32I, "lui", "lui", FormatoU, INST_TYPE_LnLn, { .opcode=OPCODE_LUI, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_AUIPC
    {RV32I, "auipc", "auipc", FormatoU, INST_TYPE_LLLn, { .opcode=OPCODE_AUIPC, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_ADD
    {RV32I, "add", "+", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SUB
    {RV32I, "sub", "-", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b000, .funct5=0b00000, .funct7=0b0100000}},
    // RV32I_AND
    {RV32I, "and", "&", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b111, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SLT
    {RV32I, "slt", "<", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b010, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SLTU
    {RV32I, "sltu", "<", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b011, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_OR
    {RV32I, "or", "|", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b110, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_XOR
    {RV32I, "xor", "^", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b100, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SLL
    {RV32I, "sll", "<<", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b001, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SRL
    {RV32I, "srl", ">>", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b101, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SRA
    {RV32I, "sra", ">>", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b101, .funct5=0b00000, .funct7=0b0100000}},
    // RV32I_JAL
    {RV32I, "jal", "jal", FormatoJ, INST_TYPE_Lnnn, { .opcode=OPCODE_JAL, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_JALR
    {RV32I, "jalr", "jalr", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_JALR, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_BEQ
    {RV32I, "beq", "==", FormatoB, INST_TYPE_nLLn, { .opcode=OPCODE_BRANCH, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_BNE
    {RV32I, "bne", "!=", FormatoB, INST_TYPE_nLLn, { .opcode=OPCODE_BRANCH, .funct3=0b001, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_BLT
    {RV32I, "blt", "<", FormatoB, INST_TYPE_nLLn, { .opcode=OPCODE_BRANCH, .funct3=0b100, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_BLTU
    {RV32I, "bltu", "<", FormatoB, INST_TYPE_nLLn, { .opcode=OPCODE_BRANCH, .funct3=0b110, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_BGE
    {RV32I, "bge", ">=", FormatoB, INST_TYPE_nLLn, { .opcode=OPCODE_BRANCH, .funct3=0b101, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_BGEU
    {RV32I, "bgeu", ">=", FormatoB, INST_TYPE_nLLn, { .opcode=OPCODE_BRANCH, .funct3=0b111, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_LB
    {RV32I, "lb", "lb", FormatoI, INST_TYPE_LLnn, { .opcode=OPCODE_LOAD, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_LBU
    {RV32I, "lbu", "lbu", FormatoI, INST_TYPE_LLnn, { .opcode=OPCODE_LOAD, .funct3=0b100, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_LH
    {RV32I, "lh", "lh", FormatoI, INST_TYPE_LLnn, { .opcode=OPCODE_LOAD, .funct3=0b001, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_LHU
    {RV32I, "lhu", "lhu", FormatoI, INST_TYPE_LLnn, { .opcode=OPCODE_LOAD, .funct3=0b101, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_LW
    {RV32I, "lw", "lw", FormatoI, INST_TYPE_LLnn, { .opcode=OPCODE_LOAD, .funct3=0b111, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SB
    {RV32I, "sb", "sb", FormatoS, INST_TYPE_nLLn, { .opcode=OPCODE_STORE, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SH
    {RV32I, "sh", "sh", FormatoS, INST_TYPE_nLLn, { .opcode=OPCODE_STORE, .funct3=0b001, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_SW
    {RV32I, "sw", "sw", FormatoS, INST_TYPE_nLLn, { .opcode=OPCODE_STORE, .funct3=0b111, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_CSRRW
    {RV32I, "csrrw", "csrrw", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_SYSTEM, .funct3=F3_CSRRW, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_CSRRS
    {RV32I, "csrrs", "csrrs", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_SYSTEM, .funct3=F3_CSRRS, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_CSRRC
    {RV32I, "csrrc", "csrrc", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_SYSTEM, .funct3=F3_CSRRC, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_CSRRWI
    {RV32I, "csrrwi", "csrrwi", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_SYSTEM, .funct3=F3_CSRRWI, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_CSRRSI
    {RV32I, "csrrsi", "csrrsi", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_SYSTEM, .funct3=F3_CSRRSI, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_CSRRCI
    {RV32I, "csrrci", "csrrci", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_SYSTEM, .funct3=F3_CSRRCI, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_ECALL
    {RV32I, "ecall", "ecall", FormatoI, INST_TYPE_nnnn, { .opcode=OPCODE_SYSTEM, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32I_EBREAK
    {RV32I, "ebreak", "ebreak", FormatoI, INST_TYPE_nnnn, { .opcode=OPCODE_SYSTEM, .funct3=0b000, .funct5=0b00001, .funct7=0b0000000}},
    // RV32M_MUL
    {RV32M, "mul", "*", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b000, .funct5=0b00000, .funct7=0b0000001}},
    // RV32M_MULH
    {RV32M, "mulh", "*", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b001, .funct5=0b00000, .funct7=0b0000001}},
    // RV32M_MULHSU
    {RV32M, "mulhsu", "*", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b010, .funct5=0b00000, .funct7=0b0000001}},
    // RV32M_MULHU
    {RV32M, "mulhu", "*", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b011, .funct5=0b00000, .funct7=0b0000001}},
    // RV32M_DIV
    {RV32M, "div", "/", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b100, .funct5=0b00000, .funct7=0b0000001}},
    // RV32M_DIVU
    {RV32M, "divu", "/", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b101, .funct5=0b00000, .funct7=0b0000001}},
    // RV32M_REM
    {RV32M, "rem", "%", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b110, .funct5=0b00000, .funct7=0b0000001}},
    // RV32M_REMU
    {RV32M, "remu", "%", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP, .funct3=0b111, .funct5=0b00000, .funct7=0b0000001}},
    // RV32F_FLW
    {RV32F, "flw", "flw", FormatoI, INST_TYPE_SLnn, { .opcode=OPCODE_LOAD_FP, .funct3=0b010, .funct5=0b00000, .funct7=0b0000000}},
    // RV32F_FSW
    {RV32F, "fsw", "fsw", FormatoS, INST_TYPE_nLSn, { .opcode=OPCODE_STORE_FP, .funct3=0b010, .funct5=0b00000, .funct7=0b0000000}},
    // RV32F_FMADD_S
    {RV32F, "fmadd.s", "*+", FormatoR4rm, INST_TYPE_SSSS, { .opcode=OPCODE_MADD, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32F_FMSUB_S
    {RV32F, "fmsub.s", "*-", FormatoR4rm, INST_TYPE_SSSS, { .opcode=OPCODE_MSUB, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32F_FNMSUB_S
    {RV32F, "fnmsub.s", "*-", FormatoR4rm, INST_TYPE_SSSS, { .opcode=OPCODE_NMSUB, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32F_FNMADD_S
    {RV32F, "fnmadd.s", "*+", FormatoR4rm, INST_TYPE_SSSS, { .opcode=OPCODE_NMADD, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32F_FADD_S
    {RV32F, "fadd.s", "+", FormatoR3rm, INST_TYPE_SSSn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV32F_FSUB_S
    {RV32F, "fsub.s", "-", FormatoR3rm, INST_TYPE_SSSn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0000100}},
    // RV32F_FMUL_S
    {RV32F, "fmul.s", "*", FormatoR3rm, INST_TYPE_SSSn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0001000}},
    // RV32F_FDIV_S
    {RV32F, "fdiv.s", "/", FormatoR3rm, INST_TYPE_SSSn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0001100}},
    // RV32F_FSQRT_S
    {RV32F, "fsqrt.s", "sqrt", FormatoR2rm, INST_TYPE_SSnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0101100}},
    // RV32F_FSGNJ_S
    {RV32F, "fsgnj.s", "sgnj", FormatoR, INST_TYPE_SSSn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0010000}},
    // RV32F_FSGNJN_S
    {RV32F, "fsgnjn.s", "sgnjn", FormatoR, INST_TYPE_SSSn, { .opcode=OPCODE_OP_FP, .funct3=0b001, .funct5=0b00000, .funct7=0b0010000}},
    // RV32F_FSGNJX_S
    {RV32F, "fsgnjx.s", "sgnjx", FormatoR, INST_TYPE_SSSn, { .opcode=OPCODE_OP_FP, .funct3=0b010, .funct5=0b00000, .funct7=0b0010000}},
    // RV32F_FMIN_S
    {RV32F, "fmin.s", "min", FormatoR, INST_TYPE_SSSn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0010100}},
    // RV32F_FMAX_S
    {RV32F, "fmax.s", "max", FormatoR, INST_TYPE_SSSn, { .opcode=OPCODE_OP_FP, .funct3=0b001, .funct5=0b00000, .funct7=0b0010100}},
    // RV32F_FCVT_W_S
    {RV32F, "fcvt.w.s", "cvt.w.s", FormatoR2rm, INST_TYPE_LSnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b1100000}},
    // RV32F_FCVT_WU_S
    {RV32F, "fcvt.wu.s", "cvt.w.s", FormatoR2rm, INST_TYPE_LSnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00001, .funct7=0b1100000}},
    // RV32F_FMV_X_W
    {RV32F, "fmv.x.w", "mv.x.w", FormatoR, INST_TYPE_LSnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b1110000}},
    // RV32F_FEQ_S
    {RV32F, "feq.s", "==", FormatoR, INST_TYPE_LSSn, { .opcode=OPCODE_OP_FP, .funct3=0b010, .funct5=0b00000, .funct7=0b1010000}},
    // RV32F_FLT_S
    {RV32F, "flt.s", "<", FormatoR, INST_TYPE_LSSn, { .opcode=OPCODE_OP_FP, .funct3=0b001, .funct5=0b00000, .funct7=0b1010000}},
    // RV32F_FLE_S
    {RV32F, "fle.s", "<=", FormatoR, INST_TYPE_LSSn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b1010000}},
    // RV32F_FCLASS_S
    {RV32F, "fclass.s", "class", FormatoR, INST_TYPE_LSnn, { .opcode=OPCODE_OP_FP, .funct3=0b001, .funct5=0b00000, .funct7=0b1110000}},
    // RV32F_FCVT_S_W
    {RV32F, "fcvt.s.w", "cvt.s.w", FormatoR2rm, INST_TYPE_SLnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b1101000}},
    // RV32F_FCVT_S_WU
    {RV32F, "fcvt.s.wu", "ctv.s.w", FormatoR2rm, INST_TYPE_SLnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00001, .funct7=0b1101000}},
    // RV32F_FMV_W_X
    {RV32F, "fmv.w.x", "mv.w.x", FormatoR, INST_TYPE_SLnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b1111000}},
    // RV32D_FLD
    {RV32D, "fld", "fld", FormatoI, INST_TYPE_DLnn, { .opcode=OPCODE_LOAD_FP, .funct3=0b011, .funct5=0b00000, .funct7=0b0000000}},
    // RV32D_FSD
    {RV32D, "fsd", "fsd", FormatoS, INST_TYPE_nLDn, { .opcode=OPCODE_STORE_FP, .funct3=0b011, .funct5=0b00000, .funct7=0b0000000}},
    // RV32D_FMADD_D
    {RV32D, "fmadd.d", "*+", FormatoR4rm, INST_TYPE_DDDD, { .opcode=OPCODE_MADD, .funct3=0b000, .funct5=0b00000, .funct7=0b0000001}},
    // RV32D_FMSUB_D
    {RV32D, "fmsub.d", "*-", FormatoR4rm, INST_TYPE_DDDD, { .opcode=OPCODE_MSUB, .funct3=0b000, .funct5=0b00000, .funct7=0b0000001}},
    // RV32D_FNMSUB_D
    {RV32D, "fnmsub.d", "*-", FormatoR4rm, INST_TYPE_DDDD, { .opcode=OPCODE_NMSUB, .funct3=0b000, .funct5=0b00000, .funct7=0b0000001}},
    // RV32D_FNMADD_D
    {RV32D, "fnmadd.d", "*+", FormatoR4rm, INST_TYPE_DDDD, { .opcode=OPCODE_NMADD, .funct3=0b000, .funct5=0b00000, .funct7=0b0000001}},
    // RV32D_FADD_D
    {RV32D, "fadd.d", "+", FormatoR3rm, INST_TYPE_DDDn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0000001}},
    // RV32D_FSUB_D
    {RV32D, "fsub.d", "-", FormatoR3rm, INST_TYPE_DDDn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0000101}},
    // RV32D_FMUL_D
    {RV32D, "fmul.d", "*", FormatoR3rm, INST_TYPE_DDDn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0001001}},
    // RV32D_FDIV_D
    {RV32D, "fdiv.d", "/", FormatoR3rm, INST_TYPE_DDDn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0001101}},
    // RV32D_FSQRT_D
    {RV32D, "fsqrt.d", "sqrt", FormatoR2rm, INST_TYPE_DDnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0101101}},
    // RV32D_FSGNJ_D
    {RV32D, "fsgnj.d", "sgnj", FormatoR, INST_TYPE_DDDn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0010001}},
    // RV32D_FSGNJN_D
    {RV32D, "fsgnjn.d", "sgnjn", FormatoR, INST_TYPE_DDDn, { .opcode=OPCODE_OP_FP, .funct3=0b001, .funct5=0b00000, .funct7=0b0010001}},
    // RV32D_FSGNJX_D
    {RV32D, "fsgnjx.d", "sgnjx", FormatoR, INST_TYPE_DDDn, { .opcode=OPCODE_OP_FP, .funct3=0b010, .funct5=0b00000, .funct7=0b0010001}},
    // RV32D_FMIN_D
    {RV32D, "fmin.d", "min", FormatoR, INST_TYPE_DDDn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0010101}},
    // RV32D_FMAX_D
    {RV32D, "fmax.d", "max", FormatoR, INST_TYPE_DDDn, { .opcode=OPCODE_OP_FP, .funct3=0b001, .funct5=0b00000, .funct7=0b0010101}},
    // RV32D_FCVT_S_D
    {RV32D, "fcvt.s.d", "cvt.s.d", FormatoR2rm, INST_TYPE_DDnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00001, .funct7=0b0100000}},
    // RV32D_FCVT_D_S
    {RV32D, "fcvt.d.s", "cvt.d.s", FormatoR2rm, INST_TYPE_DDnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b0100001}},
    // RV32D_FEQ_D
    {RV32D, "feq.d", "==", FormatoR, INST_TYPE_LDDn, { .opcode=OPCODE_OP_FP, .funct3=0b010, .funct5=0b00000, .funct7=0b1010001}},
    // RV32D_FLT_D
    {RV32D, "flt.d", "<", FormatoR, INST_TYPE_LDDn, { .opcode=OPCODE_OP_FP, .funct3=0b001, .funct5=0b00000, .funct7=0b1010001}},
    // RV32D_FLE_D
    {RV32D, "fle.d", ">=", FormatoR, INST_TYPE_LDDn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b1010001}},
    // RV32D_FCLASS_D
    {RV32D, "fclass.d", "class", FormatoR, INST_TYPE_LDnn, { .opcode=OPCODE_OP_FP, .funct3=0b001, .funct5=0b00000, .funct7=0b1110001}},
    // RV32D_FCVT_W_D
    {RV32D, "fcvt.w.d", "cvt.w.d", FormatoR2rm, INST_TYPE_LDnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b1100001}},
    // RV32D_FCVT_WU_D
    {RV32D, "fcvt.wu.d", "cvt.w.d", FormatoR2rm, INST_TYPE_LDnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00001, .funct7=0b1100001}},
    // RV32D_FCVT_D_W
    {RV32D, "fcvt.d.w", "cvt.d.w", FormatoR2rm, INST_TYPE_DLnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b1101001}},
    // RV32D_FCVT_D_WU
    {RV32D, "fcvt.d.wu", "cvt.d.wu", FormatoR2rm, INST_TYPE_DLnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00001, .funct7=0b1101001}},
    // RV32A_LR_W
    {RV32A, "lr.w", "lr", FormatoR, INST_TYPE_LLnn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0001000}},
    // RV32A_SC_W
    {RV32A, "sc.w", "sc", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0001100}},
    // RV32A_AMOSWAP_W
    {RV32A, "amoswap.w", "aswap", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0000100}},
    // RV32A_AMOADD_W
    {RV32A, "amoadd.w", "aadd", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0000000}},
    // RV32A_AMOXOR_W
    {RV32A, "amoxor.w", "axor", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0010000}},
    // RV32A_AMOAND_W
    {RV32A, "amoand.w", "aand", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0110000}},
    // RV32A_AMOOR_W
    {RV32A, "amoor.w", "aor", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0100000}},
    // RV32A_AMOMIN_W
    {RV32A, "amomin.w", "amin", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1000000}},
    // RV32A_AMOMAX_W
    {RV32A, "amomax.w", "amax", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1010000}},
    // RV32A_AMOMINU_W
    {RV32A, "amominu.w", "amin", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1100000}},
    // RV32A_AMOMAXU_W
    {RV32A, "amomaxu.w", "amax", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1110000}},
    // RV32A_LR_W_AQ
    {RV32A, "lr.w.aq", "lr.aq", FormatoR, INST_TYPE_LLnn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0001010}},
    // RV32A_SC_W_AQ
    {RV32A, "sc.w.aq", "sc.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0001110}},
    // RV32A_AMOSWAP_W_AQ
    {RV32A, "amoswap.w.aq", "aswap", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0000110}},
    // RV32A_AMOADD_W_AQ
    {RV32A, "amoadd.w.aq", "aadd", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0000010}},
    // RV32A_AMOXOR_W_AQ
    {RV32A, "amoxor.w.aq", "axor", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0010010}},
    // RV32A_AMOAND_W_AQ
    {RV32A, "amoand.w.aq", "aand", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0110010}},
    // RV32A_AMOOR_W_AQ
    {RV32A, "amoor.w.aq", "aor", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0100010}},
    // RV32A_AMOMIN_W_AQ
    {RV32A, "amomin.w.aq", "amin", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1000010}},
    // RV32A_AMOMAX_W_AQ
    {RV32A, "amomax.w.aq", "amax", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1010010}},
    // RV32A_AMOMINU_W_AQ
    {RV32A, "amominu.w.aq", "amin", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1100010}},
    // RV32A_AMOMAXU_W_AQ
    {RV32A, "amomaxu.w.aq", "amax", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1110010}},
    // RV32A_LR_W_RL
    {RV32A, "lr.w.rl", "lr.rl", FormatoR, INST_TYPE_LLnn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0001001}},
    // RV32A_SC_W_RL
    {RV32A, "sc.w.rl", "sc.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0001101}},
    // RV32A_AMOSWAP_W_RL
    {RV32A, "amoswap.w.rl", "aswap.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0000101}},
    // RV32A_AMOADD_W_RL
    {RV32A, "amoadd.w.rl", "aadd.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0000001}},
    // RV32A_AMOXOR_W_RL
    {RV32A, "amoxor.w.rl", "axor.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0010001}},
    // RV32A_AMOAND_W_RL
    {RV32A, "amoand.w.rl", "aand.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0110001}},
    // RV32A_AMOOR_W_RL
    {RV32A, "amoor.w.rl", "aor.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0100001}},
    // RV32A_AMOMIN_W_RL
    {RV32A, "amomin.w.rl", "amin.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1000001}},
    // RV32A_AMOMAX_W_RL
    {RV32A, "amomax.w.rl", "amax.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1010001}},
    // RV32A_AMOMINU_W_RL
    {RV32A, "amominu.w.rl", "amin.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1100001}},
    // RV32A_AMOMAXU_W_RL
    {RV32A, "amomaxu.w.rl", "amax.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1110001}},
    // RV32A_LR_W_AQRL
    {RV32A, "lr.w.aqrl", "lr.aqrl", FormatoR, INST_TYPE_LLnn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0001011}},
    // RV32A_SC_W_AQRL
    {RV32A, "sc.w.aqrl", "sc.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0001111}},
    // RV32A_AMOSWAP_W_AQRL
    {RV32A, "amoswap.w.aqrl", "aswap.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0000111}},
    // RV32A_AMOADD_W_AQRL
    {RV32A, "amoadd.w.aqrl", "aadd.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0000011}},
    // RV32A_AMOXOR_W_AQRL
    {RV32A, "amoxor.w.aqrl", "axor.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0010011}},
    // RV32A_AMOAND_W_AQRL
    {RV32A, "amoand.w.aqrl", "aand.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0110011}},
    // RV32A_AMOOR_W_AQRL
    {RV32A, "amoor.w.aqrl", "aor.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b0100011}},
    // RV32A_AMOMIN_W_AQRL
    {RV32A, "amomin.w.aqrl", "amin.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1000011}},
    // RV32A_AMOMAX_W_AQRL
    {RV32A, "amomax.w.aqrl", "amax.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1010011}},
    // RV32A_AMOMINU_W_AQRL
    {RV32A, "amominu.w.aqrl", "amin.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1100011}},
    // RV32A_AMOMAXU_W_AQRL
    {RV32A, "amomaxu.w.aqrl", "amax.aqlr", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b010, .funct5=0b00000, .funct7=0b1110011}},
    // RV64I_LWU
    {RV64I, "lwu", "lwu", FormatoI, INST_TYPE_LLnn, { .opcode=OPCODE_LOAD, .funct3=0b110, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_LD
    {RV64I, "ld", "ld", FormatoI, INST_TYPE_LLnn, { .opcode=OPCODE_LOAD, .funct3=0b011, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_SD
    {RV64I, "sd", "sd", FormatoS, INST_TYPE_nLLn, { .opcode=OPCODE_STORE, .funct3=0b011, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_ADDIW
    {RV64I, "addiw", "+", FormatoI, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM_32, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_SLLI
    {RV64I, "slli", "<<", FormatoIshift, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM, .funct3=0b001, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_SRLI
    {RV64I, "srli", ">>", FormatoIshift, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM, .funct3=0b101, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_SRAI
    {RV64I, "srai", ">>", FormatoIshift, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM, .funct3=0b101, .funct5=0b00000, .funct7=0b0100000}},
    // RV64I_SLLIW
    {RV64I, "slliw", "<<", FormatoIshift, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM_32, .funct3=0b001, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_SRLIW
    {RV64I, "srliw", ">>", FormatoIshift, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM_32, .funct3=0b101, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_SRAIW
    {RV64I, "sraiw", ">>", FormatoIshift, INST_TYPE_LLLn, { .opcode=OPCODE_OP_IMM_32, .funct3=0b101, .funct5=0b00000, .funct7=0b0100000}},
    // RV64I_ADDW
    {RV64I, "addw", "+", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP_32, .funct3=0b000, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_SUBW
    {RV64I, "subw", "-", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP_32, .funct3=0b000, .funct5=0b00000, .funct7=0b0100000}},
    // RV64I_SLLW
    {RV64I, "sllw", "<<", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP_32, .funct3=0b001, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_SRLW
    {RV64I, "srlw", ">>", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP_32, .funct3=0b101, .funct5=0b00000, .funct7=0b0000000}},
    // RV64I_SRAW
    {RV64I, "sraw", ">>", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP_32, .funct3=0b101, .funct5=0b00000, .funct7=0b0100000}},
    // RV64M_MULW
    {RV64M, "mulw", "+", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP_32, .funct3=0b000, .funct5=0b00000, .funct7=0b0000001}},
    // RV64M_DIVW
    {RV64M, "divw", "/", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP_32, .funct3=0b100, .funct5=0b00000, .funct7=0b0000001}},
    // RV64M_DIVUW
    {RV64M, "divuw", "/", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP_32, .funct3=0b101, .funct5=0b00000, .funct7=0b0000001}},
    // RV64M_REMW
    {RV64M, "remw", "%", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP_32, .funct3=0b110, .funct5=0b00000, .funct7=0b0000001}},
    // RV64M_REMUW
    {RV64M, "remuw", "%", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_OP_32, .funct3=0b111, .funct5=0b00000, .funct7=0b0000001}},
    // RV64A_LR_D
    {RV64A, "lr.d", "lr", FormatoR, INST_TYPE_LLnn, { .opcode=OPCODE_AMO, .funct3=0b011, .funct5=0b00000, .funct7=0b0001000}},
    // RV64A_SC_D
    {RV64A, "sc.d", "sc", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b011, .funct5=0b00000, .funct7=0b0001100}},
    // RV64A_AMOSWAP_D
    {RV64A, "amoswap.d", "aswap", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0000100}},
    // RV64A_AMOADD_D
    {RV64A, "amoadd.d", "aadd", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0000000}},
    // RV64A_AMOXOR_D
    {RV64A, "amoxor.d", "axor", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0010000}},
    // RV64A_AMOAND_D
    {RV64A, "amoand.d", "aand", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0110000}},
    // RV64A_AMOOR_D
    {RV64A, "amoor.d", "aor", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0100000}},
    // RV64A_AMOMIN_D
    {RV64A, "amomin.d", "amin", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1000000}},
    // RV64A_AMOMAX_D
    {RV64A, "amomax.d", "amax", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1010000}},
    // RV64A_AMOMINU_D
    {RV64A, "amominu.d", "amin", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1100000}},
    // RV64A_AMOMAXU_D
    {RV64A, "amomaxu.d", "amax", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1110000}},
    // RV64A_LR_D_AQ
    {RV64A, "lr.d.aq", "lr.aq", FormatoR, INST_TYPE_LLnn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0001010}},
    // RV64A_SC_D_AQ
    {RV64A, "sc.d.aq", "sc.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0001110}},
    // RV64A_AMOSWAP_D_AQ
    {RV64A, "amoswap.d.aq", "awap.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0000110}},
    // RV64A_AMOADD_D_AQ
    {RV64A, "amoadd.d.aq", "aadd.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0000010}},
    // RV64A_AMOXOR_D_AQ
    {RV64A, "amoxor.d.aq", "axor.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0010010}},
    // RV64A_AMOAND_D_AQ
    {RV64A, "amoand.d.aq", "aand.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0110010}},
    // RV64A_AMOOR_D_AQ
    {RV64A, "amoor.d.aq", "aor.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0100010}},
    // RV64A_AMOMIN_D_AQ
    {RV64A, "amomin.d.aq", "amin.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1000010}},
    // RV64A_AMOMAX_D_AQ
    {RV64A, "amomax.d.aq", "amax.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1010010}},
    // RV64A_AMOMINU_D_AQ
    {RV64A, "amominu.d.aq", "amin.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1100010}},
    // RV64A_AMOMAXU_D_AQ
    {RV64A, "amomaxu.d.aq", "amax.aq", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1110010}},
    // RV64A_LR_D_RL
    {RV64A, "lr.d.rl", "lr.rl", FormatoR, INST_TYPE_LLnn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0001001}},
    // RV64A_SC_D_RL
    {RV64A, "sc.d.rl", "sc.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0001101}},
    // RV64A_AMOSWAP_D_RL
    {RV64A, "amoswap.d.rl", "aswap.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0000101}},
    // RV64A_AMOADD_D_RL
    {RV64A, "amoadd.d.rl", "add.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0000001}},
    // RV64A_AMOXOR_D_RL
    {RV64A, "amoxor.d.rl", "axor.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0010001}},
    // RV64A_AMOAND_D_RL
    {RV64A, "amoand.d.rl", "aand.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0110001}},
    // RV64A_AMOOR_D_RL
    {RV64A, "amoor.d.rl", "aor.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0100001}},
    // RV64A_AMOMIN_D_RL
    {RV64A, "amomin.d.rl", "amin.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1000001}},
    // RV64A_AMOMAX_D_RL
    {RV64A, "amomax.d.rl", "amax.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1010001}},
    // RV64A_AMOMINU_D_RL
    {RV64A, "amominu.d.rl", "amin.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1100001}},
    // RV64A_AMOMAXU_D_RL
    {RV64A, "amomaxu.d.rl", "amax.rl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1110001}},
    // RV64A_LR_D_AQRL
    {RV64A, "lr.d.aqrl", "lr.aqrl", FormatoR, INST_TYPE_LLnn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0001011}},
    // RV64A_SC_D_AQRL
    {RV64A, "sc.d.aqrl", "sc.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0001111}},
    // RV64A_AMOSWAP_D_AQRL
    {RV64A, "amoswap.d.aqrl", "aswap.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0000111}},
    // RV64A_AMOADD_D_AQRL
    {RV64A, "amoadd.d.aqrl", "aadd.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0000011}},
    // RV64A_AMOXOR_D_AQRL
    {RV64A, "amoxor.d.aqrl", "axor.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0010011}},
    // RV64A_AMOAND_D_AQRL
    {RV64A, "amoand.d.aqrl", "aand.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0110011}},
    // RV64A_AMOOR_D_AQRL
    {RV64A, "amoor.d.aqrl", "aor.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b0100011}},
    // RV64A_AMOMIN_D_AQRL
    {RV64A, "amomin.d.aqrl", "amin.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1000011}},
    // RV64A_AMOMAX_D_AQRL
    {RV64A, "amomax.d.aqrl", "amax.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1010011}},
    // RV64A_AMOMINU_D_AQRL
    {RV64A, "amominu.d.aqrl", "amin.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1100011}},
    // RV64A_AMOMAXU_D_AQRL
    {RV64A, "amomaxu.d.aqrl", "amax.aqrl", FormatoR, INST_TYPE_LLLn, { .opcode=OPCODE_AMO, .funct3=0b111, .funct5=0b00000, .funct7=0b1110011}},
    // RV64F_FCVT_L_S
    {RV64F, "fcvt.l.s", "cvt.l.s", FormatoR2rm, INST_TYPE_LSnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00010, .funct7=0b1100000}},
    // RV64F_FCVT_LU_S
    {RV64F, "fcvt.lu.s", "cvt.l.s", FormatoR2rm, INST_TYPE_LSnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00011, .funct7=0b1100000}},
    // RV64F_FCVT_S_L
    {RV64F, "fcvt.s.l", "cvt.s.l", FormatoR2rm, INST_TYPE_SLnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00010, .funct7=0b1101000}},
    // RV64F_FCVT_S_LU
    {RV64F, "fcvt.s.lu", "cvt.s.l", FormatoR2rm, INST_TYPE_SLnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00011, .funct7=0b1101000}},
    // RV64D_FCVT_L_D
    {RV64D, "fcvt.l.d", "cvt.l.d", FormatoR2rm, INST_TYPE_LDnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00010, .funct7=0b1100001}},
    // RV64D_FCVT_LU_D
    {RV64D, "fcvt.lu.d", "cvt.l.d", FormatoR2rm, INST_TYPE_LDnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00011, .funct7=0b1100001}},
    // RV64D_FMV_X_D
    {RV64D, "fmv.x.d", "mv.x.d", FormatoR, INST_TYPE_LDnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b1110001}},
    // RV64D_FCVT_D_L
    {RV64D, "fcvt.d.l", "cvt.d.l", FormatoR2rm, INST_TYPE_DLnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00010, .funct7=0b1101001}},
    // RV64D_FCVT_D_LU
    {RV64D, "fcvt.d.lu", "cvt.d.l", FormatoR2rm, INST_TYPE_DLnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00011, .funct7=0b1101001}},
    // RV64D_FMV_D_X
    {RV64D, "fmv.d.x", "mv.d.x", FormatoR, INST_TYPE_DLnn, { .opcode=OPCODE_OP_FP, .funct3=0b000, .funct5=0b00000, .funct7=0b1111001}}
};

void decode_error(
        dword PC,
        format_decode_type decode,
        char * fail
        ) {
    char opcode[8];
    char funct3[4];
    char funct5[6];
    char funct7[8];

    itobin(decode.opcode, opcode, 7);
    itobin(decode.funct3, funct3, 3);
    itobin(decode.funct5, funct5, 5);
    itobin(decode.funct7, funct7, 7);

    fprintf(stderr, "error: PC = " F_DWORD ". Instrucción no implementada [!%s] (opcode: %s func3: %s func5: %s func7: %s)\n",
            PC, fail, opcode, funct3, funct5, funct7);
    exit(1);
}

/**
 * Decodifica la instrucción a partir de los campos opcode, func3, func5 y func7
 */
codop_t obtener_decodificacion(
    dword PC, format_decode_type decode,
    char **p_nemo, int *p_subfmt, formato_t *p_format
) {
    codop_t codop = -1;

#define SET_DECODE_INFO(_codop, _nemo, _subfmt) do { \
    codop = (_codop); \
    *p_nemo = (_nemo); \
    *p_subfmt = (_subfmt); \
} while(0)

    switch (decode.opcode) {
        case OPCODE_OP_IMM: // opcode
            switch (decode.funct3) {
                case 0b000: // funct3
                    SET_DECODE_INFO(RV32I_ADDI, "addi", FMT_INT_RRI);
                    break;
                case 0b010: // funct3
                    SET_DECODE_INFO(RV32I_SLTI, "slti", FMT_INT_RRI);
                    break;
                case 0b011: // funct3
                    SET_DECODE_INFO(RV32I_SLTIU, "sltiu", FMT_INT_RRI);
                    break;
                case 0b111: // funct3
                    SET_DECODE_INFO(RV32I_ANDI, "andi", FMT_INT_RRI);
                    break;
                case 0b110: // funct3
                    SET_DECODE_INFO(RV32I_ORI, "ori", FMT_INT_RRI);
                    break;
                case 0b100: // funct3
                    SET_DECODE_INFO(RV32I_XORI, "xori", FMT_INT_RRI);
                    break;
                case 0b001: // funct3
                    SET_DECODE_INFO(RV64I_SLLI, "slli", FMT_INT_RRSH);
                    break;
                case 0b101: // funct3
                    switch (decode.funct7 & 0b1111110) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV64I_SRLI, "srli", FMT_INT_RRSH);
                            break;
                        case 0b0100000: // funct7
                            SET_DECODE_INFO(RV64I_SRAI, "srai", FMT_INT_RRSH);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        case OPCODE_LUI: // opcode
            SET_DECODE_INFO(RV32I_LUI, "lui", FMT_INT_RI);
            break; 
        case OPCODE_AUIPC: // opcode
            SET_DECODE_INFO(RV32I_AUIPC, "auipc", FMT_INT_RA);
            break; 
        case OPCODE_OP: // opcode
            switch (decode.funct3) {
                case 0b000: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV32I_ADD, "add", FMT_INT_RRR);
                            break;
                        case 0b0100000: // funct7
                            SET_DECODE_INFO(RV32I_SUB, "sub", FMT_INT_RRR);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV32M_MUL, "mul", FMT_INT_RRR);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b111: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV32I_AND, "and", FMT_INT_RRR);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV32M_REMU, "remu", FMT_INT_RRR);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b010: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV32I_SLT, "slt", FMT_INT_RRR);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV32M_MULHSU, "mulhsu", FMT_INT_RRR);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b011: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV32I_SLTU, "sltu", FMT_INT_RRR);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV32M_MULHU, "mulhu", FMT_INT_RRR);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b110: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV32I_OR, "or", FMT_INT_RRR);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV32M_REM, "rem", FMT_INT_RRR);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b100: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV32I_XOR, "xor", FMT_INT_RRR);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV32M_DIV, "div", FMT_INT_RRR);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b001: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV32I_SLL, "sll", FMT_INT_RRR);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV32M_MULH, "mulh", FMT_INT_RRR);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b101: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV32I_SRL, "srl", FMT_INT_RRR);
                            break;
                        case 0b0100000: // funct7
                            SET_DECODE_INFO(RV32I_SRA, "sra", FMT_INT_RRR);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV32M_DIVU, "divu", FMT_INT_RRR);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        case OPCODE_JAL: // opcode
            SET_DECODE_INFO(RV32I_JAL, "jal", FMT_J_RA);
            break; 
        case OPCODE_JALR: // opcode
            SET_DECODE_INFO(RV32I_JALR, "jalr", FMT_J_RRA);
            break; 
        case OPCODE_BRANCH: // opcode
            switch (decode.funct3) {
                case 0b000: // funct3
                    SET_DECODE_INFO(RV32I_BEQ, "beq", FMT_INT_B_RRA);
                    break;
                case 0b001: // funct3
                    SET_DECODE_INFO(RV32I_BNE, "bne", FMT_INT_B_RRA);
                    break;
                case 0b100: // funct3
                    SET_DECODE_INFO(RV32I_BLT, "blt", FMT_INT_B_RRA);
                    break;
                case 0b110: // funct3
                    SET_DECODE_INFO(RV32I_BLTU, "bltu", FMT_INT_B_RRA);
                    break;
                case 0b101: // funct3
                    SET_DECODE_INFO(RV32I_BGE, "bge", FMT_INT_B_RRA);
                    break;
                case 0b111: // funct3
                    SET_DECODE_INFO(RV32I_BGEU, "bgeu", FMT_INT_B_RRA);
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        case OPCODE_LOAD: // opcode
            switch (decode.funct3) {
                case 0b000: // funct3
                    SET_DECODE_INFO(RV32I_LB, "lb", FMT_INT_L_RSB);
                    break;
                case 0b100: // funct3
                    SET_DECODE_INFO(RV32I_LBU, "lbu", FMT_INT_L_RSB);
                    break;
                case 0b001: // funct3
                    SET_DECODE_INFO(RV32I_LH, "lh", FMT_INT_L_RSB);
                    break;
                case 0b101: // funct3
                    SET_DECODE_INFO(RV32I_LHU, "lhu", FMT_INT_L_RSB);
                    break;
                case 0b111: // funct3
                    SET_DECODE_INFO(RV32I_LW, "lw", FMT_INT_L_RSB);
                    break;
                case 0b110: // funct3
                    SET_DECODE_INFO(RV64I_LWU, "lwu", FMT_INT_L_RSB);
                    break;
                case 0b011: // funct3
                    SET_DECODE_INFO(RV64I_LD, "ld", FMT_INT_L_RSB);
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        case OPCODE_STORE: // opcode
            switch (decode.funct3) {
                case 0b000: // funct3
                    SET_DECODE_INFO(RV32I_SB, "sb", FMT_INT_S_RSB);
                    break;
                case 0b001: // funct3
                    SET_DECODE_INFO(RV32I_SH, "sh", FMT_INT_S_RSB);
                    break;
                case 0b111: // funct3
                    SET_DECODE_INFO(RV32I_SW, "sw", FMT_INT_S_RSB);
                    break;
                case 0b011: // funct3
                    SET_DECODE_INFO(RV64I_SD, "sd", FMT_INT_S_RSB);
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        case OPCODE_SYSTEM: // opcode
            switch (decode.funct3) {
                case F3_CSRRW: // funct3
                    SET_DECODE_INFO(RV32I_CSRRW, "csrrw", FMT_CSR_RxR);
                    break;
                case F3_CSRRS: // funct3
                    SET_DECODE_INFO(RV32I_CSRRS, "csrrs", FMT_CSR_RxR);
                    break;
                case F3_CSRRC: // funct3
                    SET_DECODE_INFO(RV32I_CSRRC, "csrrc", FMT_CSR_RxR);
                    break;
                case F3_CSRRWI: // funct3
                    SET_DECODE_INFO(RV32I_CSRRWI, "csrrwi", FMT_CSR_RxI);
                    break;
                case F3_CSRRSI: // funct3
                    SET_DECODE_INFO(RV32I_CSRRSI, "csrrsi", FMT_CSR_RxI);
                    break;
                case F3_CSRRCI: // funct3
                    SET_DECODE_INFO(RV32I_CSRRCI, "csrrci", FMT_CSR_RxI);
                    break;
                case 0b000: // funct3
                    switch (decode.funct5) {
                        case 0b00000: // funct5
                            SET_DECODE_INFO(RV32I_ECALL, "ecall", FMT_INT_ECALL);
                            break;
                        case 0b00001: // funct5
                            SET_DECODE_INFO(RV32I_EBREAK, "ebreak", FMT_INT_EBREAK);
                            break;
                        default:
                            decode_error(PC, decode, "funct5");
                    } // end funct5
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        case OPCODE_LOAD_FP: // opcode
            switch (decode.funct3) {
                case 0b010: // funct3
                    SET_DECODE_INFO(RV32F_FLW, "flw", FMT_FP_L_FSB);
                    break;
                case 0b011: // funct3
                    SET_DECODE_INFO(RV32D_FLD, "fld", FMT_FP_L_FSB);
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        case OPCODE_STORE_FP: // opcode
            switch (decode.funct3) {
                case 0b010: // funct3
                    SET_DECODE_INFO(RV32F_FSW, "fsw", FMT_FP_S_FSB);
                    break;
                case 0b011: // funct3
                    SET_DECODE_INFO(RV32D_FSD, "fsd", FMT_FP_S_FSB);
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        case OPCODE_MADD: // opcode
            switch (decode.funct7 & 0b0000011) {
                case 0b0000000: // funct7
                    SET_DECODE_INFO(RV32F_FMADD_S, "fmadd.s", FMT_FP_FFFFr);
                    break;
                case 0b0000001: // funct7
                    SET_DECODE_INFO(RV32D_FMADD_D, "fmadd.d", FMT_FP_FFFFr);
                    break;
                default:
                    decode_error(PC, decode, "funct7");
            } // end funct7
            break; 
        case OPCODE_MSUB: // opcode
            switch (decode.funct7 & 0b0000011) {
                case 0b0000000: // funct7
                    SET_DECODE_INFO(RV32F_FMSUB_S, "fmsub.s", FMT_FP_FFFFr);
                    break;
                case 0b0000001: // funct7
                    SET_DECODE_INFO(RV32D_FMSUB_D, "fmsub.d", FMT_FP_FFFFr);
                    break;
                default:
                    decode_error(PC, decode, "funct7");
            } // end funct7
            break; 
        case OPCODE_NMSUB: // opcode
            switch (decode.funct7 & 0b0000011) {
                case 0b0000000: // funct7
                    SET_DECODE_INFO(RV32F_FNMSUB_S, "fnmsub.s", FMT_FP_FFFFr);
                    break;
                case 0b0000001: // funct7
                    SET_DECODE_INFO(RV32D_FNMSUB_D, "fnmsub.d", FMT_FP_FFFFr);
                    break;
                default:
                    decode_error(PC, decode, "funct7");
            } // end funct7
            break; 
        case OPCODE_NMADD: // opcode
            switch (decode.funct7 & 0b0000011) {
                case 0b0000000: // funct7
                    SET_DECODE_INFO(RV32F_FNMADD_S, "fnmadd.s", FMT_FP_FFFFr);
                    break;
                case 0b0000001: // funct7
                    SET_DECODE_INFO(RV32D_FNMADD_D, "fnmadd.d", FMT_FP_FFFFr);
                    break;
                default:
                    decode_error(PC, decode, "funct7");
            } // end funct7
            break; 
        case OPCODE_OP_FP: // opcode
            switch (decode.funct7) {
                case 0b0000000: // funct7
                    SET_DECODE_INFO(RV32F_FADD_S, "fadd.s", FMT_FP_FFFr);
                    break;
                case 0b0000100: // funct7
                    SET_DECODE_INFO(RV32F_FSUB_S, "fsub.s", FMT_FP_FFFr);
                    break;
                case 0b0001000: // funct7
                    SET_DECODE_INFO(RV32F_FMUL_S, "fmul.s", FMT_FP_FFFr);
                    break;
                case 0b0001100: // funct7
                    SET_DECODE_INFO(RV32F_FDIV_S, "fdiv.s", FMT_FP_FFFr);
                    break;
                case 0b0101100: // funct7
                    SET_DECODE_INFO(RV32F_FSQRT_S, "fsqrt.s", FMT_FP_FFr);
                    break;
                case 0b0010000: // funct7
                    switch (decode.funct3) {
                        case 0b000: // funct3
                            SET_DECODE_INFO(RV32F_FSGNJ_S, "fsgnj.s", FMT_FP_FFF);
                            break;
                        case 0b001: // funct3
                            SET_DECODE_INFO(RV32F_FSGNJN_S, "fsgnjn.s", FMT_FP_FFF);
                            break;
                        case 0b010: // funct3
                            SET_DECODE_INFO(RV32F_FSGNJX_S, "fsgnjx.s", FMT_FP_FFF);
                            break;
                        default:
                            decode_error(PC, decode, "funct3");
                    } // end funct3
                    break;
                case 0b0010100: // funct7
                    switch (decode.funct3) {
                        case 0b000: // funct3
                            SET_DECODE_INFO(RV32F_FMIN_S, "fmin.s", FMT_FP_FFF);
                            break;
                        case 0b001: // funct3
                            SET_DECODE_INFO(RV32F_FMAX_S, "fmax.s", FMT_FP_FFF);
                            break;
                        default:
                            decode_error(PC, decode, "funct3");
                    } // end funct3
                    break;
                case 0b1100000: // funct7
                    switch (decode.funct5) {
                        case 0b00000: // funct5
                            SET_DECODE_INFO(RV32F_FCVT_W_S, "fcvt.w.s", FMT_FP_RFr);
                            break;
                        case 0b00001: // funct5
                            SET_DECODE_INFO(RV32F_FCVT_WU_S, "fcvt.wu.s", FMT_FP_RFr);
                            break;
                        case 0b00010: // funct5
                            SET_DECODE_INFO(RV64F_FCVT_L_S, "fcvt.l.s", FMT_FP_RFr);
                            break;
                        case 0b00011: // funct5
                            SET_DECODE_INFO(RV64F_FCVT_LU_S, "fcvt.lu.s", FMT_FP_RFr);
                            break;
                        default:
                            decode_error(PC, decode, "funct5");
                    } // end funct5
                    break;
                case 0b1110000: // funct7
                    switch (decode.funct3) {
                        case 0b000: // funct3
                            SET_DECODE_INFO(RV32F_FMV_X_W, "fmv.x.w", FMT_FP_RF);
                            break;
                        case 0b001: // funct3
                            SET_DECODE_INFO(RV32F_FCLASS_S, "fclass.s", FMT_FP_RF);
                            break;
                        default:
                            decode_error(PC, decode, "funct3");
                    } // end funct3
                    break;
                case 0b1010000: // funct7
                    switch (decode.funct3) {
                        case 0b010: // funct3
                            SET_DECODE_INFO(RV32F_FEQ_S, "feq.s", FMT_FP_RFF);
                            break;
                        case 0b001: // funct3
                            SET_DECODE_INFO(RV32F_FLT_S, "flt.s", FMT_FP_RFF);
                            break;
                        case 0b000: // funct3
                            SET_DECODE_INFO(RV32F_FLE_S, "fle.s", FMT_FP_RFF);
                            break;
                        default:
                            decode_error(PC, decode, "funct3");
                    } // end funct3
                    break;
                case 0b1101000: // funct7
                    switch (decode.funct5) {
                        case 0b00000: // funct5
                            SET_DECODE_INFO(RV32F_FCVT_S_W, "fcvt.s.w", FMT_FP_FRr);
                            break;
                        case 0b00001: // funct5
                            SET_DECODE_INFO(RV32F_FCVT_S_WU, "fcvt.s.wu", FMT_FP_FRr);
                            break;
                        case 0b00010: // funct5
                            SET_DECODE_INFO(RV64F_FCVT_S_L, "fcvt.s.l", FMT_FP_FRr);
                            break;
                        case 0b00011: // funct5
                            SET_DECODE_INFO(RV64F_FCVT_S_LU, "fcvt.s.lu", FMT_FP_FRr);
                            break;
                        default:
                            decode_error(PC, decode, "funct5");
                    } // end funct5
                    break;
                case 0b1111000: // funct7
                    SET_DECODE_INFO(RV32F_FMV_W_X, "fmv.w.x", FMT_FP_FR);
                    break;
                case 0b0000001: // funct7
                    SET_DECODE_INFO(RV32D_FADD_D, "fadd.d", FMT_FP_FFFr);
                    break;
                case 0b0000101: // funct7
                    SET_DECODE_INFO(RV32D_FSUB_D, "fsub.d", FMT_FP_FFFr);
                    break;
                case 0b0001001: // funct7
                    SET_DECODE_INFO(RV32D_FMUL_D, "fmul.d", FMT_FP_FFFr);
                    break;
                case 0b0001101: // funct7
                    SET_DECODE_INFO(RV32D_FDIV_D, "fdiv.d", FMT_FP_FFFr);
                    break;
                case 0b0101101: // funct7
                    SET_DECODE_INFO(RV32D_FSQRT_D, "fsqrt.d", FMT_FP_FFr);
                    break;
                case 0b0010001: // funct7
                    switch (decode.funct3) {
                        case 0b000: // funct3
                            SET_DECODE_INFO(RV32D_FSGNJ_D, "fsgnj.d", FMT_FP_FFF);
                            break;
                        case 0b001: // funct3
                            SET_DECODE_INFO(RV32D_FSGNJN_D, "fsgnjn.d", FMT_FP_FFF);
                            break;
                        case 0b010: // funct3
                            SET_DECODE_INFO(RV32D_FSGNJX_D, "fsgnjx.d", FMT_FP_FFF);
                            break;
                        default:
                            decode_error(PC, decode, "funct3");
                    } // end funct3
                    break;
                case 0b0010101: // funct7
                    switch (decode.funct3) {
                        case 0b000: // funct3
                            SET_DECODE_INFO(RV32D_FMIN_D, "fmin.d", FMT_FP_FFF);
                            break;
                        case 0b001: // funct3
                            SET_DECODE_INFO(RV32D_FMAX_D, "fmax.d", FMT_FP_FFF);
                            break;
                        default:
                            decode_error(PC, decode, "funct3");
                    } // end funct3
                    break;
                case 0b0100000: // funct7
                    SET_DECODE_INFO(RV32D_FCVT_S_D, "fcvt.s.d", FMT_FP_FFr);
                    break;
                case 0b0100001: // funct7
                    SET_DECODE_INFO(RV32D_FCVT_D_S, "fcvt.d.s", FMT_FP_FFr);
                    break;
                case 0b1010001: // funct7
                    switch (decode.funct3) {
                        case 0b010: // funct3
                            SET_DECODE_INFO(RV32D_FEQ_D, "feq.d", FMT_FP_RFF);
                            break;
                        case 0b001: // funct3
                            SET_DECODE_INFO(RV32D_FLT_D, "flt.d", FMT_FP_RFF);
                            break;
                        case 0b000: // funct3
                            SET_DECODE_INFO(RV32D_FLE_D, "fle.d", FMT_FP_RFF);
                            break;
                        default:
                            decode_error(PC, decode, "funct3");
                    } // end funct3
                    break;
                case 0b1110001: // funct7
                    switch (decode.funct3) {
                        case 0b001: // funct3
                            SET_DECODE_INFO(RV32D_FCLASS_D, "fclass.d", FMT_FP_RF);
                            break;
                        case 0b000: // funct3
                            SET_DECODE_INFO(RV64D_FMV_X_D, "fmv.x.d", FMT_FP_RF);
                            break;
                        default:
                            decode_error(PC, decode, "funct3");
                    } // end funct3
                    break;
                case 0b1100001: // funct7
                    switch (decode.funct5) {
                        case 0b00000: // funct5
                            SET_DECODE_INFO(RV32D_FCVT_W_D, "fcvt.w.d", FMT_FP_RFr);
                            break;
                        case 0b00001: // funct5
                            SET_DECODE_INFO(RV32D_FCVT_WU_D, "fcvt.wu.d", FMT_FP_RFr);
                            break;
                        case 0b00010: // funct5
                            SET_DECODE_INFO(RV64D_FCVT_L_D, "fcvt.l.d", FMT_FP_RFr);
                            break;
                        case 0b00011: // funct5
                            SET_DECODE_INFO(RV64D_FCVT_LU_D, "fcvt.lu.d", FMT_FP_RFr);
                            break;
                        default:
                            decode_error(PC, decode, "funct5");
                    } // end funct5
                    break;
                case 0b1101001: // funct7
                    switch (decode.funct5) {
                        case 0b00000: // funct5
                            SET_DECODE_INFO(RV32D_FCVT_D_W, "fcvt.d.w", FMT_FP_FRr);
                            break;
                        case 0b00001: // funct5
                            SET_DECODE_INFO(RV32D_FCVT_D_WU, "fcvt.d.wu", FMT_FP_FRr);
                            break;
                        case 0b00010: // funct5
                            SET_DECODE_INFO(RV64D_FCVT_D_L, "fcvt.d.l", FMT_FP_FRr);
                            break;
                        case 0b00011: // funct5
                            SET_DECODE_INFO(RV64D_FCVT_D_LU, "fcvt.d.lu", FMT_FP_FRr);
                            break;
                        default:
                            decode_error(PC, decode, "funct5");
                    } // end funct5
                    break;
                case 0b1111001: // funct7
                    SET_DECODE_INFO(RV64D_FMV_D_X, "fmv.d.x", FMT_FP_FR);
                    break;
                default:
                    decode_error(PC, decode, "funct7");
            } // end funct7
            break; 
        case OPCODE_AMO: // opcode
            switch (decode.funct3) {
                case 0b010: // funct3
                    switch (decode.funct7) {
                        case 0b0001000: // funct7
                            SET_DECODE_INFO(RV32A_LR_W, "lr.w", FMT_INT_RB);
                            break;
                        case 0b0001100: // funct7
                            SET_DECODE_INFO(RV32A_SC_W, "sc.w", FMT_INT_RRB);
                            break;
                        case 0b0000100: // funct7
                            SET_DECODE_INFO(RV32A_AMOSWAP_W, "amoswap.w", FMT_INT_RRB);
                            break;
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV32A_AMOADD_W, "amoadd.w", FMT_INT_RRB);
                            break;
                        case 0b0010000: // funct7
                            SET_DECODE_INFO(RV32A_AMOXOR_W, "amoxor.w", FMT_INT_RRB);
                            break;
                        case 0b0110000: // funct7
                            SET_DECODE_INFO(RV32A_AMOAND_W, "amoand.w", FMT_INT_RRB);
                            break;
                        case 0b0100000: // funct7
                            SET_DECODE_INFO(RV32A_AMOOR_W, "amoor.w", FMT_INT_RRB);
                            break;
                        case 0b1000000: // funct7
                            SET_DECODE_INFO(RV32A_AMOMIN_W, "amomin.w", FMT_INT_RRB);
                            break;
                        case 0b1010000: // funct7
                            SET_DECODE_INFO(RV32A_AMOMAX_W, "amomax.w", FMT_INT_RRB);
                            break;
                        case 0b1100000: // funct7
                            SET_DECODE_INFO(RV32A_AMOMINU_W, "amominu.w", FMT_INT_RRB);
                            break;
                        case 0b1110000: // funct7
                            SET_DECODE_INFO(RV32A_AMOMAXU_W, "amomaxu.w", FMT_INT_RRB);
                            break;
                        case 0b0001010: // funct7
                            SET_DECODE_INFO(RV32A_LR_W_AQ, "lr.w.aq", FMT_INT_RB);
                            break;
                        case 0b0001110: // funct7
                            SET_DECODE_INFO(RV32A_SC_W_AQ, "sc.w.aq", FMT_INT_RRB);
                            break;
                        case 0b0000110: // funct7
                            SET_DECODE_INFO(RV32A_AMOSWAP_W_AQ, "amoswap.w.aq", FMT_INT_RRB);
                            break;
                        case 0b0000010: // funct7
                            SET_DECODE_INFO(RV32A_AMOADD_W_AQ, "amoadd.w.aq", FMT_INT_RRB);
                            break;
                        case 0b0010010: // funct7
                            SET_DECODE_INFO(RV32A_AMOXOR_W_AQ, "amoxor.w.aq", FMT_INT_RRB);
                            break;
                        case 0b0110010: // funct7
                            SET_DECODE_INFO(RV32A_AMOAND_W_AQ, "amoand.w.aq", FMT_INT_RRB);
                            break;
                        case 0b0100010: // funct7
                            SET_DECODE_INFO(RV32A_AMOOR_W_AQ, "amoor.w.aq", FMT_INT_RRB);
                            break;
                        case 0b1000010: // funct7
                            SET_DECODE_INFO(RV32A_AMOMIN_W_AQ, "amomin.w.aq", FMT_INT_RRB);
                            break;
                        case 0b1010010: // funct7
                            SET_DECODE_INFO(RV32A_AMOMAX_W_AQ, "amomax.w.aq", FMT_INT_RRB);
                            break;
                        case 0b1100010: // funct7
                            SET_DECODE_INFO(RV32A_AMOMINU_W_AQ, "amominu.w.aq", FMT_INT_RRB);
                            break;
                        case 0b1110010: // funct7
                            SET_DECODE_INFO(RV32A_AMOMAXU_W_AQ, "amomaxu.w.aq", FMT_INT_RRB);
                            break;
                        case 0b0001001: // funct7
                            SET_DECODE_INFO(RV32A_LR_W_RL, "lr.w.rl", FMT_INT_RB);
                            break;
                        case 0b0001101: // funct7
                            SET_DECODE_INFO(RV32A_SC_W_RL, "sc.w.rl", FMT_INT_RRB);
                            break;
                        case 0b0000101: // funct7
                            SET_DECODE_INFO(RV32A_AMOSWAP_W_RL, "amoswap.w.rl", FMT_INT_RRB);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV32A_AMOADD_W_RL, "amoadd.w.rl", FMT_INT_RRB);
                            break;
                        case 0b0010001: // funct7
                            SET_DECODE_INFO(RV32A_AMOXOR_W_RL, "amoxor.w.rl", FMT_INT_RRB);
                            break;
                        case 0b0110001: // funct7
                            SET_DECODE_INFO(RV32A_AMOAND_W_RL, "amoand.w.rl", FMT_INT_RRB);
                            break;
                        case 0b0100001: // funct7
                            SET_DECODE_INFO(RV32A_AMOOR_W_RL, "amoor.w.rl", FMT_INT_RRB);
                            break;
                        case 0b1000001: // funct7
                            SET_DECODE_INFO(RV32A_AMOMIN_W_RL, "amomin.w.rl", FMT_INT_RRB);
                            break;
                        case 0b1010001: // funct7
                            SET_DECODE_INFO(RV32A_AMOMAX_W_RL, "amomax.w.rl", FMT_INT_RRB);
                            break;
                        case 0b1100001: // funct7
                            SET_DECODE_INFO(RV32A_AMOMINU_W_RL, "amominu.w.rl", FMT_INT_RRB);
                            break;
                        case 0b1110001: // funct7
                            SET_DECODE_INFO(RV32A_AMOMAXU_W_RL, "amomaxu.w.rl", FMT_INT_RRB);
                            break;
                        case 0b0001011: // funct7
                            SET_DECODE_INFO(RV32A_LR_W_AQRL, "lr.w.aqrl", FMT_INT_RB);
                            break;
                        case 0b0001111: // funct7
                            SET_DECODE_INFO(RV32A_SC_W_AQRL, "sc.w.aqrl", FMT_INT_RRB);
                            break;
                        case 0b0000111: // funct7
                            SET_DECODE_INFO(RV32A_AMOSWAP_W_AQRL, "amoswap.w.aqrl", FMT_INT_RRB);
                            break;
                        case 0b0000011: // funct7
                            SET_DECODE_INFO(RV32A_AMOADD_W_AQRL, "amoadd.w.aqrl", FMT_INT_RRB);
                            break;
                        case 0b0010011: // funct7
                            SET_DECODE_INFO(RV32A_AMOXOR_W_AQRL, "amoxor.w.aqrl", FMT_INT_RRB);
                            break;
                        case 0b0110011: // funct7
                            SET_DECODE_INFO(RV32A_AMOAND_W_AQRL, "amoand.w.aqrl", FMT_INT_RRB);
                            break;
                        case 0b0100011: // funct7
                            SET_DECODE_INFO(RV32A_AMOOR_W_AQRL, "amoor.w.aqrl", FMT_INT_RRB);
                            break;
                        case 0b1000011: // funct7
                            SET_DECODE_INFO(RV32A_AMOMIN_W_AQRL, "amomin.w.aqrl", FMT_INT_RRB);
                            break;
                        case 0b1010011: // funct7
                            SET_DECODE_INFO(RV32A_AMOMAX_W_AQRL, "amomax.w.aqrl", FMT_INT_RRB);
                            break;
                        case 0b1100011: // funct7
                            SET_DECODE_INFO(RV32A_AMOMINU_W_AQRL, "amominu.w.aqrl", FMT_INT_RRB);
                            break;
                        case 0b1110011: // funct7
                            SET_DECODE_INFO(RV32A_AMOMAXU_W_AQRL, "amomaxu.w.aqrl", FMT_INT_RRB);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b011: // funct3
                    switch (decode.funct7) {
                        case 0b0001000: // funct7
                            SET_DECODE_INFO(RV64A_LR_D, "lr.d", FMT_INT_RB);
                            break;
                        case 0b0001100: // funct7
                            SET_DECODE_INFO(RV64A_SC_D, "sc.d", FMT_INT_RRB);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b111: // funct3
                    switch (decode.funct7) {
                        case 0b0000100: // funct7
                            SET_DECODE_INFO(RV64A_AMOSWAP_D, "amoswap.d", FMT_INT_RRB);
                            break;
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV64A_AMOADD_D, "amoadd.d", FMT_INT_RRB);
                            break;
                        case 0b0010000: // funct7
                            SET_DECODE_INFO(RV64A_AMOXOR_D, "amoxor.d", FMT_INT_RRB);
                            break;
                        case 0b0110000: // funct7
                            SET_DECODE_INFO(RV64A_AMOAND_D, "amoand.d", FMT_INT_RRB);
                            break;
                        case 0b0100000: // funct7
                            SET_DECODE_INFO(RV64A_AMOOR_D, "amoor.d", FMT_INT_RRB);
                            break;
                        case 0b1000000: // funct7
                            SET_DECODE_INFO(RV64A_AMOMIN_D, "amomin.d", FMT_INT_RRB);
                            break;
                        case 0b1010000: // funct7
                            SET_DECODE_INFO(RV64A_AMOMAX_D, "amomax.d", FMT_INT_RRB);
                            break;
                        case 0b1100000: // funct7
                            SET_DECODE_INFO(RV64A_AMOMINU_D, "amominu.d", FMT_INT_RRB);
                            break;
                        case 0b1110000: // funct7
                            SET_DECODE_INFO(RV64A_AMOMAXU_D, "amomaxu.d", FMT_INT_RRB);
                            break;
                        case 0b0001010: // funct7
                            SET_DECODE_INFO(RV64A_LR_D_AQ, "lr.d.aq", FMT_INT_RB);
                            break;
                        case 0b0001110: // funct7
                            SET_DECODE_INFO(RV64A_SC_D_AQ, "sc.d.aq", FMT_INT_RRB);
                            break;
                        case 0b0000110: // funct7
                            SET_DECODE_INFO(RV64A_AMOSWAP_D_AQ, "amoswap.d.aq", FMT_INT_RRB);
                            break;
                        case 0b0000010: // funct7
                            SET_DECODE_INFO(RV64A_AMOADD_D_AQ, "amoadd.d.aq", FMT_INT_RRB);
                            break;
                        case 0b0010010: // funct7
                            SET_DECODE_INFO(RV64A_AMOXOR_D_AQ, "amoxor.d.aq", FMT_INT_RRB);
                            break;
                        case 0b0110010: // funct7
                            SET_DECODE_INFO(RV64A_AMOAND_D_AQ, "amoand.d.aq", FMT_INT_RRB);
                            break;
                        case 0b0100010: // funct7
                            SET_DECODE_INFO(RV64A_AMOOR_D_AQ, "amoor.d.aq", FMT_INT_RRB);
                            break;
                        case 0b1000010: // funct7
                            SET_DECODE_INFO(RV64A_AMOMIN_D_AQ, "amomin.d.aq", FMT_INT_RRB);
                            break;
                        case 0b1010010: // funct7
                            SET_DECODE_INFO(RV64A_AMOMAX_D_AQ, "amomax.d.aq", FMT_INT_RRB);
                            break;
                        case 0b1100010: // funct7
                            SET_DECODE_INFO(RV64A_AMOMINU_D_AQ, "amominu.d.aq", FMT_INT_RRB);
                            break;
                        case 0b1110010: // funct7
                            SET_DECODE_INFO(RV64A_AMOMAXU_D_AQ, "amomaxu.d.aq", FMT_INT_RRB);
                            break;
                        case 0b0001001: // funct7
                            SET_DECODE_INFO(RV64A_LR_D_RL, "lr.d.rl", FMT_INT_RB);
                            break;
                        case 0b0001101: // funct7
                            SET_DECODE_INFO(RV64A_SC_D_RL, "sc.d.rl", FMT_INT_RRB);
                            break;
                        case 0b0000101: // funct7
                            SET_DECODE_INFO(RV64A_AMOSWAP_D_RL, "amoswap.d.rl", FMT_INT_RRB);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV64A_AMOADD_D_RL, "amoadd.d.rl", FMT_INT_RRB);
                            break;
                        case 0b0010001: // funct7
                            SET_DECODE_INFO(RV64A_AMOXOR_D_RL, "amoxor.d.rl", FMT_INT_RRB);
                            break;
                        case 0b0110001: // funct7
                            SET_DECODE_INFO(RV64A_AMOAND_D_RL, "amoand.d.rl", FMT_INT_RRB);
                            break;
                        case 0b0100001: // funct7
                            SET_DECODE_INFO(RV64A_AMOOR_D_RL, "amoor.d.rl", FMT_INT_RRB);
                            break;
                        case 0b1000001: // funct7
                            SET_DECODE_INFO(RV64A_AMOMIN_D_RL, "amomin.d.rl", FMT_INT_RRB);
                            break;
                        case 0b1010001: // funct7
                            SET_DECODE_INFO(RV64A_AMOMAX_D_RL, "amomax.d.rl", FMT_INT_RRB);
                            break;
                        case 0b1100001: // funct7
                            SET_DECODE_INFO(RV64A_AMOMINU_D_RL, "amominu.d.rl", FMT_INT_RRB);
                            break;
                        case 0b1110001: // funct7
                            SET_DECODE_INFO(RV64A_AMOMAXU_D_RL, "amomaxu.d.rl", FMT_INT_RRB);
                            break;
                        case 0b0001011: // funct7
                            SET_DECODE_INFO(RV64A_LR_D_AQRL, "lr.d.aqrl", FMT_INT_RB);
                            break;
                        case 0b0001111: // funct7
                            SET_DECODE_INFO(RV64A_SC_D_AQRL, "sc.d.aqrl", FMT_INT_RRB);
                            break;
                        case 0b0000111: // funct7
                            SET_DECODE_INFO(RV64A_AMOSWAP_D_AQRL, "amoswap.d.aqrl", FMT_INT_RRB);
                            break;
                        case 0b0000011: // funct7
                            SET_DECODE_INFO(RV64A_AMOADD_D_AQRL, "amoadd.d.aqrl", FMT_INT_RRB);
                            break;
                        case 0b0010011: // funct7
                            SET_DECODE_INFO(RV64A_AMOXOR_D_AQRL, "amoxor.d.aqrl", FMT_INT_RRB);
                            break;
                        case 0b0110011: // funct7
                            SET_DECODE_INFO(RV64A_AMOAND_D_AQRL, "amoand.d.aqrl", FMT_INT_RRB);
                            break;
                        case 0b0100011: // funct7
                            SET_DECODE_INFO(RV64A_AMOOR_D_AQRL, "amoor.d.aqrl", FMT_INT_RRB);
                            break;
                        case 0b1000011: // funct7
                            SET_DECODE_INFO(RV64A_AMOMIN_D_AQRL, "amomin.d.aqrl", FMT_INT_RRB);
                            break;
                        case 0b1010011: // funct7
                            SET_DECODE_INFO(RV64A_AMOMAX_D_AQRL, "amomax.d.aqrl", FMT_INT_RRB);
                            break;
                        case 0b1100011: // funct7
                            SET_DECODE_INFO(RV64A_AMOMINU_D_AQRL, "amominu.d.aqrl", FMT_INT_RRB);
                            break;
                        case 0b1110011: // funct7
                            SET_DECODE_INFO(RV64A_AMOMAXU_D_AQRL, "amomaxu.d.aqrl", FMT_INT_RRB);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        case OPCODE_OP_IMM_32: // opcode
            switch (decode.funct3) {
                case 0b000: // funct3
                    SET_DECODE_INFO(RV64I_ADDIW, "addiw", FMT_INT_RRI);
                    break;
                case 0b001: // funct3
                    SET_DECODE_INFO(RV64I_SLLIW, "slliw", FMT_INT_RRSH);
                    break;
                case 0b101: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV64I_SRLIW, "srliw", FMT_INT_RRSH);
                            break;
                        case 0b0100000: // funct7
                            SET_DECODE_INFO(RV64I_SRAIW, "sraiw", FMT_INT_RRSH);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        case OPCODE_OP_32: // opcode
            switch (decode.funct3) {
                case 0b000: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV64I_ADDW, "addw", FMT_INT_RRR);
                            break;
                        case 0b0100000: // funct7
                            SET_DECODE_INFO(RV64I_SUBW, "subw", FMT_INT_RRR);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV64M_MULW, "mulw", FMT_INT_RRR);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b001: // funct3
                    SET_DECODE_INFO(RV64I_SLLW, "sllw", FMT_INT_RRR);
                    break;
                case 0b101: // funct3
                    switch (decode.funct7) {
                        case 0b0000000: // funct7
                            SET_DECODE_INFO(RV64I_SRLW, "srlw", FMT_INT_RRR);
                            break;
                        case 0b0100000: // funct7
                            SET_DECODE_INFO(RV64I_SRAW, "sraw", FMT_INT_RRR);
                            break;
                        case 0b0000001: // funct7
                            SET_DECODE_INFO(RV64M_DIVUW, "divuw", FMT_INT_RRR);
                            break;
                        default:
                            decode_error(PC, decode, "funct7");
                    } // end funct7
                    break;
                case 0b100: // funct3
                    SET_DECODE_INFO(RV64M_DIVW, "divw", FMT_INT_RRR);
                    break;
                case 0b110: // funct3
                    SET_DECODE_INFO(RV64M_REMW, "remw", FMT_INT_RRR);
                    break;
                case 0b111: // funct3
                    SET_DECODE_INFO(RV64M_REMUW, "remuw", FMT_INT_RRR);
                    break;
                default:
                    decode_error(PC, decode, "funct3");
            } // end funct3
            break; 
        default:
            decode_error(PC, decode, "opcode");
    } // end opcode

    switch (*p_subfmt) {
        case FMT_INT_RRI:
        case FMT_J_RRA:
        case FMT_INT_L_RSB:
        case FMT_CSR_RxR:
        case FMT_CSR_RxI:
        case FMT_INT_ECALL:
        case FMT_INT_EBREAK:
        case FMT_FP_L_FSB:
            *p_format = FormatoI;
            break;
        case FMT_INT_RRSH:
            *p_format = FormatoIshift;
            break;
        case FMT_INT_RI:
        case FMT_INT_RA:
            *p_format = FormatoU;
            break;
        case FMT_INT_RRR:
        case FMT_INT_RB:
        case FMT_INT_RRB:
        case FMT_FP_FFF:
        case FMT_FP_FF:
        case FMT_FP_RF:
        case FMT_FP_RFF:
        case FMT_FP_FR:
            *p_format = FormatoR;
            break;
        case FMT_J_RA:
            *p_format = FormatoJ;
            break;
        case FMT_INT_B_RRA:
            *p_format = FormatoB;
            break;
        case FMT_INT_S_RSB:
        case FMT_FP_S_FSB:
            *p_format = FormatoS;
            break;
        case FMT_FP_FFFFr:
            *p_format = FormatoR4rm;
            break;
        case FMT_FP_FFFr:
            *p_format = FormatoR3rm;
            break;
        case FMT_FP_FFr:
        case FMT_FP_RFr:
        case FMT_FP_FRr:
            *p_format = FormatoR2rm;
            break;
        default:
            fprintf(stderr, "error: Invalid subformat (%d)", *p_subfmt);
            exit(1);
    } // end format

    return codop;
}
