/**
 * @file html-style.h
 *
 * Departamento de Informática de Sistemas y Computadores (DISCA)
 * Universidad Politécnica de Valencia.
 *
 * @author Sergio Sáez <ssaez@disca.upv.es>
 * @author Pedro López <plopez@disca.upv.es>
 *
 * @brief
 *    Cabecera para las funciones de generación de hojas de estilos
 *
 * DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
 *
 * @copyright [CC BY-NC-ND 4.0]
 *   Esta obra está bajo una licencia de Creative Commons Atribución-NoComercial-SinDerivadas
 *   Para evitar dudas, no se tiene permiso bajo esta Licencia para compartir Material Adaptado.
 *   Más detalles en https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.es
 */

#ifndef html_style_H
#define html_style_H

/*** Definiciones externas *************************************************/

#ifndef html_style_C

// CSS string
extern char * aic_style_css_string;

// Función que esribe el fichero 'aic-style.css'
void escribe_aic_style_css();

#endif

#endif /* Include html-style.h */
