/**
 * @file html_style.c
 *
 * Departamento de Informática de Sistemas y Computadores (DISCA)
 * Universidad Politécnica de Valencia.
 *
 * @author Sergio Sáez <ssaez@disca.upv.es>
 * @author Pedro López <plopez@disca.upv.es>
 *
 * @brief
 *    Contiene las funciones para la generación de las hojas de estilos
 *
 * DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
 *
 * @copyright [CC BY-NC-ND 4.0]
 *   Esta obra está bajo una licencia de Creative Commons Atribución-NoComercial-SinDerivadas
 *   Para evitar dudas, no se tiene permiso bajo esta Licencia para compartir Material Adaptado.
 *   Más detalles en https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.es
 */

#define html_style_C

/***** Definiciones Externas **********************************/

#include <stdlib.h>
#include <stdio.h>

#include "html-style.h"

/***** Variables **********************************************/

char * aic_style_css_string =
    "\n"
    "html, body, table {\n"
    "    font-family: Courier, Times, serif;\n"
    "    font-size: 10pt;\n"
    "    line-height: 100%;\n"
    "}\n"
    "\n"
    "td.address {\n"
    "    text-align: left;\n"
    "    white-space: nowrap;\n"
    "    padding: 0.1em 0.5em;\n"
    "    background-color: #ddeeff;\n"
    "}\n"
    "\n"
    ".crono td small {\n"
    "    font-size: 80%;\n"
    "}\n"
    "\n"
    ".crono td i {\n"
    "    color: #666;\n"
    "}\n"
    "\n"
    ".old td {\n"
    "    color: #aaa;\n"
    "    font-style: italic;\n"
    "}\n"
    "\n"
    ".field {\n"
    "    display: inline-block;\n"
    "    font-size: 90%;\n"
    "    height: 1.1em;\n"
    "    text-align: center;\n"
    "    padding: 4px 0 0 0;\n"
    "    border: 1px solid black\n"
    "}\n"
    "\n"
    "table.config th, table.config td {\n"
    "    padding-top: 0.3em;\n"
    "    padding-left: 0.3em;\n"
    "    white-space: nowrap;\n"
    "}\n"
    "\n"
    "table.config th {\n"
    "    background-color: #ccddff;\n"
    "    text-align: left;\n"
    "    font-weight: normal;\n"
    "}\n"
    "\n"
    "table.config td, table.stats td {\n"
    "    background-color: #eeeeee;\n"
    "}\n"
    "\n"
    "table.config td.header {\n"
    "    background-color: #ddeeff;\n"
    "    min-width: 12em;\n"
    "}\n"
    "\n"
    "table.config td.text {\n"
    "    text-align: left;\n"
    "    min-width: 16em;\n"
    "}\n"
    "\n"
    "table.config th.value, table.config td.value {\n"
    "    text-align: center;\n"
    "    width: 6em;\n"
    "    padding-left: 0.3em;\n"
    "    padding-right: 0.3em;\n"
    "}\n"
    "\n"
    "table.stats th {\n"
    "    background-color: #ccddff;\n"
    "    padding-left: 0.3em;\n"
    "    padding-right: 0.3em;\n"
    "    font-weight: normal;\n"
    "}\n"
    "\n"
    "table.stats td {\n"
    "    text-align: center;\n"
    "}\n"
    "\n"
    ".cache th, .memoria th {\n"
    "    background-color: #ccddff;\n"
    "    padding: 0.3em 0.3em 0.1em 0.3em;\n"
    "    width: 2.5em;\n"
    "    white-space: nowrap;\n"
    "}\n"
    "\n"
    ".cache th.time, .memoria th.time {\n"
    "    padding: 0.3em 0.5em 0.1em 0.5em;\n"
    "}\n"
    "\n"
    ".cache td, .memoria td {\n"
    "    text-align: center;\n"
    "    white-space: nowrap;\n"
    "}\n"
    "\n"
    ".cache tr, .memoria tr {\n"
    "    background-color: #eee;\n"
    "}\n"
    "\n"
    ".cache td.blocked, .memoria td.blocked {\n"
    "    font-style: italic;\n"
    "}\n"
    "\n"
    "table.oper {\n"
    "    margin-top: 0.3em;\n"
    "}\n"
    "\n"
    "th.index {\n"
    "    min-width: 6em;\n"
    "}\n"
    "\n"
    "th.address {\n"
    "    min-width: 6em;\n"
    "}\n"
    "\n"
    "th.oper {\n"
    "    min-width: 6em;\n"
    "}\n"
    "\n"
    "th.state {\n"
    "    min-width: 10em;\n"
    "}\n"
    "\n"
    "th.signal {\n"
    "    min-width: 5em;\n"
    "}\n"
    "\n"
    "td.old {\n"
    "    color: #888;\n"
    "    font-style: italic;\n"
    "}\n"
    "\n"
    "td.code {\n"
    "    white-space: nowrap;\n"
    "    font-size: 75%;\n"
    "}\n"
    "\n"
    "td.cancelled {\n"
    "    text-decoration: line-through;\n"
    "}\n";

/***** Funciones **********************************************/

/**
 * Imprime la hoja de estilos 'aic-style.css'
 */
void escribe_aic_style_css() {

    FILE * f_output;

    f_output = fopen("aic-style.css", "w");
    if (f_output == NULL) {
        fprintf(stderr, "Error creando 'aic-style.css'\n");
        exit(1);
    } /* endif */

    fputs(aic_style_css_string, f_output);

    fclose(f_output);
}
